# .rubocop.yml

AllCops:
  Exclude:
    - 'Rakefile'
    - '*/.rake'
    - 'bin/*'
    - '.git/**/*'
    - 'db/*schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/swagger_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/integration/*'
    - Gemfile
    - Gemfile.lock
    - config/**/*
    - config.ru

# Disable the Style/Documentation check
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
